version: '3.8'
services:
  tomcat:
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./target/psychosupport-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/psychosupport-1.0-SNAPSHOT.war
    restart: on-failure